# ----------------------------
# Makefile Options
# ----------------------------

NAME = Calc2Key
ARCHIVED = NO
DESCRIPTION = "Calc2KeyCE by David Malenke"
COMPRESSED = NO
BSSHEAP_LOW = D031F6

CFLAGS = -Wall -Wextra -O3
CXXFLAGS = -Wall -Wextra -O3
# ----------------------------

include $(shell cedev-config --makefile)
