# ----------------------------
# Makefile Options
# ----------------------------

NAME        ?= CALC2KEY
COMPRESSED  ?= YES
ICON        ?= iconc.png
DESCRIPTION ?= "Calc2KEYCE"
ARCHIVED ?= NO

CFLAGS ?= -Wall -Wextra -Oz
CXXFLAGS ?= -Wall -Wextra -Oz

# ----------------------------

ifndef CEDEV
$(error CEDEV environment path variable is not set)
endif

include $(CEDEV)/meta/makefile.mk
